<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.dhis2.demo</groupId>
  <artifactId>dhis2-demo-server</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <packaging>pom</packaging>
  <name>DHIS2 Demo Server</name>

  <modules>
    <module>content</module>
    <module>distro</module>
  </modules>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <openmrs.sdk.version>6.8.0</openmrs.sdk.version>
  </properties>

  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.openmrs.maven.plugins</groupId>
          <artifactId>openmrs-sdk-maven-plugin</artifactId>
          <version>${openmrs.sdk.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>