#!/usr/bin/env python3
import os, re, subprocess, sys, time

R = "/home/ubuntu/dhis2-demo-server"
os.chdir(R)
def sh(*a, **k):
    return subprocess.run(a, capture_output=True, text=True, **k)
def L(m=""):
    print(m, flush=True)

L("WAR cleanup: decision = build artifact (186MB un-pushable via GitHub LFS). Steps:")
L("  1) untrack the 186MB WAR pointer (worktree file stays -> compose keeps working)")
L("  2) .gitignore it so it can never sneak back into a ref (or an LFS range) again")
L("  3) commit the new build script (build-patched-war.sh) that regenerates the WAR")
L("     at boot from the STOCK war + the TRACKED small patched omods (which upload fine)")
L("  4) git lfs push the two small omods (verified uploadable) then push the ref")
L("")

WT = "openmrs-forms/above-five-treatment-register/openmrs-patched.war"
EMODS = [
    "openmrs-forms/above-five-treatment-register/coreapps-1.34.0-patched.omod",
    "openmrs-forms/login-login/referenceapplication-2.12.0-patched.omod",
]

# --- sanity: the WAR blob is 186MB real, the omods are 3.9MB+1.9MB real ---
for p in [WT] + EMODS:
    sz = os.path.getsize(p) if os.path.isfile(p) else -1
    L("  %-74s %s" % (p.split("/")[-1], "%s" % (sz if sz >= 0 else "MISSING")))

# --- 1) untrack only the WAR (keep omods tracked) ---
r = sh("git", "rm", "--cached", "--", WT)
L("  git rm --cached war  rc=%d  %s" % (r.returncode, r.stdout.strip() or r.stderr.strip()))
r = sh("git", "check-ignore", "-v", WT)
L("  ignore check  : %s" % (r.stdout.strip() or "(not yet ignored)"))

# --- 2) add to .gitignore (force, even if exists) ---
gi = open(".gitignore", "a")
line = "\n# 186MB patched WAR - build artifact, NOT versioned (regenerated by build-patched-war.sh)\n%s\n" % WT
if WT not in open(".gitignore").read():
    gi.write(line)
gi.close()
r = sh("git", "check-ignore", "-v", WT)
L("  ignore AFTER  : %s" % (r.stdout.strip() or "!! still not ignored"))
r = sh("git", "status", "-s", "--", WT)
L("  status war    : %s" % (r.stdout.strip() or "(clean - untracked+ignored)"))

# --- the omods are tracked in git (as lfs/pointer?) or plain? ---
L("")
L("  omod lfs-ursage: %s" % sh("git", "lfs", "ls-files").stdout.strip().replace("\n", " | "))

L("")
L("STEP 4: lfs push TWO small omods (own transport, each <4MB) -> then ref push")
t0 = time.time()
log = open("/tmp/opencode/omodpush.log", "w")
p = subprocess.Popen(["git", "lfs", "push", "--all", "origin",
                      "0d927f9ccc011544668022ea4bf481c16111ef43"],
                     stdout=log, stderr=subprocess.STDOUT, bufsize=1)
while p.poll() is None:
    ln = log.readline()
    if ln.strip():
        L("  +%3ds  %s" % (int(time.time() - t0), ln.strip()))
    time.sleep(15)
    if time.time() - t0 > 1500:
        p.kill(); L("TIMEOUT"); break
rc = p.wait()
L("lfs push rc=%d  elapsed=%ds" % (rc, int(time.time() - t0)))
for ln in sh("tail", "-c", "400", "/tmp/opencode/omodpush.log").stdout.splitlines():
    L("    " + ln)
if rc == 0:
    L("")
    L("STEP 5: ref push (pure git - LFS was its own phase; omod pointer objects now on github)")
    r = sh("git", "push", "origin", "HEAD:refs/heads/main")
    L("  git push rc=%d  %s" % (r.returncode, (r.stdout + r.stderr).strip()))
sys.exit(rc if rc != 0 else 0)
