# DHIS2 configuration
connection.dialect = org.hibernate.dialect.PostgreSQLDialect
connection.driver_class = org.postgresql.Driver
connection.url = jdbc:postgresql://db:5432/dhis
connection.username = dhis
connection.password = dhis
# Encryption
encryption.password = aes-256-password
# Monitoring
monitoring.api.enabled = false
# System
system.monitoring.app.open.compare = false
