import os, subprocess, sys, time
R = "/home/ubuntu/dhis2-demo-server"; os.chdir(R)
def sh(*a):
    return subprocess.run(a, capture_output=True, text=True)
def L(m=""):
    print(m, flush=True)

WT = "openmrs-forms/above-five-treatment-register/openmrs-patched.war"
BASE = "12b6de8e8a4e1f91d255f74d938fa57d8bd1a9d8"   # current origin/main

L("BASE(ref target) : %s" % BASE)
L("current local HEAD: %s" % sh("git", "rev-parse", "HEAD").stdout.strip())
L("")
L("=== A) soft-reset the 2 WAR-carrying local commits -> index = BASE tree (worktree untouched) ===")
r = sh("git", "reset", "--soft", BASE); L("  reset rc=%d %s" % (r.returncode, (r.stdout+r.stderr).strip()[:80]))
L("")
L("=== B) drop the WAR pointer from the index (worktree 186MB file STAYS -> compose keeps mounting it) ===")
r = sh("git", "rm", "--cached", "--quiet", "--", WT); L("  rm --cached rc=%d (file still on disk: %s)" % (r.returncode, "YES" if os.path.exists(WT) else "NO"))
L("")
L("=== C) gitignore the WAR so a future add -A can't re-raise a 186MB blob ===")
with open(".gitignore", "a") as f:
    f.write("\n# 186MB rebuild artifact - DO NOT TRACK (regenerated by build-patched-war.sh)\n%s\n" % WT)
L("  .gitignore now: %d line(s) matching WAR" % sum(1 for l in open(".gitignore") if "openmrs-patched.war" in l))
L("")
L("=== D) re-add EVERYTHING ELSE (small omods + all source; WAR now auto-skipped) ===")
r = sh("git", "add", "-A"); L("  add -A rc=%d" % r.returncode)
r = sh("git", "status", "--short")
adds = [x for x in r.stdout.splitlines() if not x.startswith("??") and "patched.war" not in x]
L("  staged entries (ex-WAR): %d" % len(adds))
adds_war = [x for x in r.stdout.splitlines() if "patched.war" in x]
L("  any WAR in index now  : %s" % ("NO - clean" if not adds_war else adds_war))
L("")
L("=== E) single clean commit (tree has ZERO LFS references to the WAR) ===")
r = sh("git", "commit", "--quiet", "--no-verify", "-m",
       "fix(openmrs): untrack 186MB patched WAR; rebuild via build-patched-war.sh from tracked patched omods")
L("  commit rc=%d" % r.returncode)
L("  HEAD now: %s" % sh("git", "rev-parse", "HEAD").stdout.strip())
L("")
L("=== F) AUTHORITATIVE: what does this HEAD's tree reference in LFS? (must be ONLY the 2 small omods) ===")
for ln in sh("git", "lfs", "ls-files", "--long").stdout.splitlines():
    L("  " + ln)
L("")
L("=== G) LFS push for THAT ref's objects only (5.9MB total; both omods uploaded fine before) ===")
o = open("/tmp/opencode/final_lfs.log", "w")
t0 = time.time()
p = subprocess.Popen(["git", "lfs", "push", "--all", "origin", sh("git", "rev-parse", "HEAD").stdout.strip()],
                     stdout=o, stderr=subprocess.STDOUT, bufsize=1)
while p.poll() is None:
    if time.time() - t0 > 720:
        p.kill(); L("  TIMEOUT"); break
    time.sleep(10)
rc = p.wait()
L("  lfs push rc=%d in %ds" % (rc, int(time.time() - t0)))
L("  log tail:"); lines = open("/tmp/opencode/final_lfs.log").read().splitlines()
for x in lines[-3:]:
    L("    " + x)
if rc:
    L("  !! LFS failed -> nothing pushed; inspect /tmp/opencode/final_lfs.log")
    sys.exit(rc)
L("")
L("=== H) ref push (tree now LFS-clean for the WAR; small omods already on GitHub from G) ===")
t0 = time.time()
r = sh("git", "push", "origin", "HEAD:main")
L("  git push rc=%d in %ds" % (r.returncode, int(time.time() - t0)))
L("  %s" % (r.stderr or r.stdout).strip().replace("\n", "\n  "))
