# Filtered from openmrs-image/openmrs-distro.properties (resolved production
# baseline) during the distro build. Contains variable references resolved by
# maven-resources-plugin, e.g. ${project.version} -> version.
name=${project.name}
version=${project.version}
content.${contentArtifact}=${contentVersion}
content.${contentArtifact}.groupId=${contentGroup}
content.${contentArtifact}.namespace=
db.h2.supported=false
omod.addresshierarchy=3.0.0-SNAPSHOT
omod.allergyui=1.8.7
omod.appframework=2.20.0-SNAPSHOT
omod.appointments=2.2.0
omod.appointments.groupId=org.bahmni.module
omod.appointmentscheduling=2.0.0
omod.appointmentschedulingui=2.0.0
omod.appui=1.18.0
omod.attachments=4.0.0
omod.authentication=2.3.0
omod.authenticationui=1.4.0-SNAPSHOT
omod.bedmanagement=7.3.0-SNAPSHOT
omod.calculation=2.0.0
omod.coreapps=4.0.0-SNAPSHOT
omod.dispensing=2.1.0-SNAPSHOT
omod.edtriageapp=2.2.0-SNAPSHOT
omod.emr=2.3.0
omod.emrapi=3.5.0-SNAPSHOT
omod.event=4.0.0
omod.event.groupId=org.openmrs
omod.fhir2=4.3.0-SNAPSHOT
omod.growthchart=2.1.0
omod.htmlformentry=7.3.0-SNAPSHOT
omod.htmlformentryui=3.3.0-SNAPSHOT
omod.htmlwidgets=2.0.1
omod.idgen=6.0.0-SNAPSHOT
omod.initializer=2.12.0
omod.labtrackingapp=1.3.0-SNAPSHOT
omod.legacyui=2.3.0-SNAPSHOT
omod.metadatamapping=2.0.0
omod.namephonetics=1.19.0
omod.o3forms=2.3.0
omod.openconceptlab=3.2.0
omod.owa=1.15.0
omod.paperrecord=1.4.1
omod.pihapps=1.2.0-SNAPSHOT
omod.pihcore=2.2.0-SNAPSHOT
omod.printer=1.6.0
omod.queue=3.1.0-SNAPSHOT
omod.radiologyapp=1.9.0-SNAPSHOT
omod.registrationapp=1.30.0-SNAPSHOT
omod.registrationcore=1.13.0
omod.reporting=2.2.0-SNAPSHOT
omod.reportingrest=2.1.0-SNAPSHOT
omod.reportingui=1.15.0-SNAPSHOT
omod.serialization.xstream=0.3.0
omod.serialization.xstream.type=omod
omod.spa=3.0.0
omod.teleconsultation=2.0.0
omod.teleconsultation.groupId=org.bahmni.module
omod.uicommons=3.2.0-SNAPSHOT
omod.uiframework=4.0.0
omod.uilibrary=2.0.7
omod.webservices.rest=3.5.0-SNAPSHOT
owa.labworkflow=2.0.0-SNAPSHOT
property.initializer.startup.load=disabled
property.pih.config.default=sierraLeone,sierraLeone-mongo
property.pih.config.prompt=Specify PIH config (sierraLeone,sierraLeone-mongo | sierraLeone,sierraLeone-falaba | sierraLeone,sierraLeone-sinkunia | sierraLeone,sierraLeone-kgh | sierraLeone,sierraLeone-wellbody)?
spa.artifactId=${frontendArtifact}
spa.groupId=${frontendGroup}
spa.includes=${frontendArtifact}-${frontendVersion}
spa.type=zip
spa.version=${frontendVersion}
war.openmrs=2.8.9